// See https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8
export default [
  'account_id',
  'account_name',
  'campaign_id',
  'campaign_name',
  'adset_id',
  'adset_name',
  'ad_id',
  'ad_name',
  'date_start',
  'date_stop',
  'objective',
  'impressions',
  'clicks',
  'ctr',
  'unique_impressions',
  'unique_clicks',
  'unique_ctr',
  'spend',
  'frequency',
  'reach',
];
