import { dataTypeEnum } from '../utils/tableau';

// See https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8
export default [
  // Dimension columns
  { id: 'account_id', alias: 'Account ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'account_name', alias: 'Account Name', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'campaign_id', alias: 'Campaign ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'campaign_name', alias: 'Campaign Name', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'adset_id', alias: 'AdSet ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'adset_name', alias: 'AdSet Name', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'ad_id', alias: 'Ad ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'ad_name', alias: 'Ad Name', columnRole: 'dimension', dataType: dataTypeEnum.string },
  // Breakdown columns
  { id: 'age', alias: 'Age', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'country', alias: 'Country', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'gender', alias: 'Gender', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'frequency_value', alias: 'Frequency Value', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'hourly_stats_aggregated_by_advertiser_time_zone',
    alias: 'Hour (Advertiser)',
    columnRole: 'dimension',
    dataType: dataTypeEnum.string },
  { id: 'hourly_stats_aggregated_by_audience_time_zone',
    alias: 'Hour (Audience)',
    columnRole: 'dimension',
    dataType: dataTypeEnum.string },
  { id: 'impression_device', alias: 'Impression Device', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'place_page_id', alias: 'Place Page ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'placement', alias: 'Placement', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'publisher_platform', alias: 'Publisher Platform', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'platform_position', alias: 'Platform Position', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'device_platform', alias: 'Device Platform', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'product_id', alias: 'Product ID', columnRole: 'dimension', dataType: dataTypeEnum.string },
  { id: 'region', alias: 'Region', columnRole: 'dimension', dataType: dataTypeEnum.string },
  // Value columns
  { id: 'date_start', alias: 'Date Start', dataType: dataTypeEnum.date },
  { id: 'date_stop', alias: 'Date Stop', dataType: dataTypeEnum.date },
  { id: 'objective', alias: 'Objective', dataType: dataTypeEnum.string },
  { id: 'impressions', alias: 'Impressions', dataType: dataTypeEnum.int },
  { id: 'clicks', alias: 'Clicks', dataType: dataTypeEnum.int },
  { id: 'call_to_action_clicks', alias: 'Call To Action Clicks', dataType: dataTypeEnum.int },
  { id: 'inline_link_clicks', alias: 'Inline Link Clicks', dataType: dataTypeEnum.int },
  { id: 'cost_per_inline_link_click', alias: 'Cost per Inline Link Click', dataType: dataTypeEnum.float },
  { id: 'cost_per_unique_inline_link_click', alias: 'Cost per Unique Inline Link Click', dataType: dataTypeEnum.float },
  { id: 'ctr', alias: 'CTR', dataType: dataTypeEnum.float },
  { id: 'inline_link_click_ctr', alias: 'Inline Link Click CTR', dataType: dataTypeEnum.float },
  { id: 'unique_clicks', alias: 'Unique Clicks', dataType: dataTypeEnum.int },
  { id: 'unique_ctr', alias: 'Unique CTR', dataType: dataTypeEnum.float },
  { id: 'spend', alias: 'Spend', dataType: dataTypeEnum.float },
  { id: 'frequency', alias: 'Frequency', dataType: dataTypeEnum.float },
  { id: 'reach', alias: 'Reach', dataType: dataTypeEnum.int },
  { id: 'social_reach', alias: 'Social Reach', dataType: dataTypeEnum.int },
  { id: 'score', alias: 'Relevance Score', dataType: dataTypeEnum.int },
  { id: 'positive_feedback', alias: 'Positive Feedback', dataType: dataTypeEnum.string },
  { id: 'negative_feedback', alias: 'Negative Feedback', dataType: dataTypeEnum.string },
  // Video Engagement columns
  { id: 'actions', alias: '3-Second Video Views', dataType: dataTypeEnum.float },
  { id: 'video_10_sec_watched_actions', alias: '10-Second Video Views', dataType: dataTypeEnum.float },
  { id: 'cost_per_10_sec_video_view', alias: 'Cost per 10-Second Video View', dataType: dataTypeEnum.float },
  { id: 'video_avg_percent_watched_actions', alias: 'Video Percentage Watched', dataType: dataTypeEnum.float },
  { id: 'video_p25_watched_actions', alias: 'Video Watches at 25%', dataType: dataTypeEnum.int },
  { id: 'video_p50_watched_actions', alias: 'Video Watches at 50%', dataType: dataTypeEnum.int },
  { id: 'video_p75_watched_actions', alias: 'Video Watches at 75%', dataType: dataTypeEnum.int },
  { id: 'video_p95_watched_actions', alias: 'Video Watches at 95%', dataType: dataTypeEnum.int },
  { id: 'video_p100_watched_actions', alias: 'Video Watches at 100%', dataType: dataTypeEnum.int },
];
