// See https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8
export default [
  { id: 'account_id', name: 'Account ID' },
  { id: 'account_name', name: 'Account Name' },
  { id: 'campaign_id', name: 'Campaign ID' },
  { id: 'campaign_name', name: 'Campaign Name' },
  { id: 'adset_id', name: 'Adset ID' },
  { id: 'adset_name', name: 'Adset Name' },
  { id: 'ad_id', name: 'Ad ID' },
  { id: 'ad_name', name: 'Ad Name' },
  { id: 'date_start', name: 'Date Start' },
  { id: 'date_stop', name: 'Date Stop' },
  { id: 'objective', name: 'Objective' },
  { id: 'impressions', name: 'Impressions' },
  { id: 'clicks', name: 'Clicks' },
  { id: 'ctr', name: 'CTR' },
  { id: 'unique_impressions', name: 'Unique Impressions' },
  { id: 'unique_clicks', name: 'Unique Clicks' },
  { id: 'unique_ctr', name: 'Unique CTR' },
  { id: 'spend', name: 'Spend' },
  { id: 'frequency', name: '' },
  { id: 'reach', name: 'Frequency' },
  { id: 'relevance_score', name: 'Relevance Score' },
];
