const tableau = window.tableau;

// See https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8
export default [
  // Dimension columns
  { id: 'account_id', alias: 'Account ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'account_name', alias: 'Account Name', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'campaign_id', alias: 'Campaign ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'campaign_name', alias: 'Campaign Name', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'adset_id', alias: 'AdSet ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'adset_name', alias: 'AdSet Name', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'ad_id', alias: 'Ad ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'ad_name', alias: 'Ad Name', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  // Breakdown columns
  { id: 'age', alias: 'Age', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'country', alias: 'Country', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'gender', alias: 'Gender', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'frequency_value', alias: 'Frequency Value', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'hourly_stats_aggregated_by_advertiser_time_zone',
    alias: 'Hour (Advertiser)',
    columnRole: 'dimension',
    dataType: tableau.dataTypeEnum.string },
  { id: 'hourly_stats_aggregated_by_audience_time_zone',
    alias: 'Hour (Audience)',
    columnRole: 'dimension',
    dataType: tableau.dataTypeEnum.string },
  { id: 'impression_device', alias: 'Impression Device', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'place_page_id', alias: 'Place Page ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'placement', alias: 'Placement', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'publisher_platform', alias: 'Publisher Platform', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'platform_position', alias: 'Platform Position', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'device_platform', alias: 'Device Platform', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'product_id', alias: 'Product ID', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  { id: 'region', alias: 'Region', columnRole: 'dimension', dataType: tableau.dataTypeEnum.string },
  // Value columns
  { id: 'date_start', alias: 'Date Start', dataType: tableau.dataTypeEnum.date },
  { id: 'date_stop', alias: 'Date Stop', dataType: tableau.dataTypeEnum.date },
  { id: 'objective', alias: 'Objective', dataType: tableau.dataTypeEnum.string },
  { id: 'impressions', alias: 'Impressions', dataType: tableau.dataTypeEnum.int },
  { id: 'clicks', alias: 'Clicks', dataType: tableau.dataTypeEnum.int },
  { id: 'ctr', alias: 'CTR', dataType: tableau.dataTypeEnum.float },
  { id: 'unique_impressions', alias: 'Unique Impressions', dataType: tableau.dataTypeEnum.int },
  { id: 'unique_clicks', alias: 'Unique Clicks', dataType: tableau.dataTypeEnum.int },
  { id: 'unique_ctr', alias: 'Unique CTR', dataType: tableau.dataTypeEnum.float },
  { id: 'spend', alias: 'Spend', dataType: tableau.dataTypeEnum.float },
  { id: 'frequency', alias: 'Frequency', dataType: tableau.dataTypeEnum.float },
  { id: 'reach', alias: 'Reach', dataType: tableau.dataTypeEnum.int },
  { id: 'score', alias: 'Relevance Score', dataType: tableau.dataTypeEnum.int },
  { id: 'positive_feedback', alias: 'Positive Feedback', dataType: tableau.dataTypeEnum.string },
  { id: 'negative_feedback', alias: 'Negative Feedback', dataType: tableau.dataTypeEnum.string },
];
