export default [
  { id: 'age', name: 'Age' },
  { id: 'country', name: 'Country' },
  { id: 'gender', name: 'Gender' },
  { id: 'frequency_value', name: 'Frequency Value' },
  { id: 'hourly_stats_aggregated_by_advertiser_time_zone', name: 'Hour (Advertiser)' },
  { id: 'hourly_stats_aggregated_by_audience_time_zone', name: 'Hour (Audience)' },
  { id: 'impression_device', name: 'Impression Device' },
  { id: 'place_page_id', name: 'Place Page ID' },
  { id: 'placement', name: 'Placement' },
  { id: 'publisher_platform', name: 'Publisher Platform' },
  { id: 'platform_position', name: 'Platform Position' },
  { id: 'device_platform', name: 'Device Platform' },
  { id: 'product_id', name: 'Product ID' },
  { id: 'region', name: 'Region' },
];
