// See https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8
export default [
  { id: 'account_id', name: 'Account ID' },
  { id: 'account_name', name: 'Account Name' },
  { id: 'campaign_id', name: 'Campaign ID' },
  { id: 'campaign_name', name: 'Campaign Name' },
  { id: 'adset_id', name: 'Adset ID' },
  { id: 'adset_name', name: 'Adset Name' },
  { id: 'ad_id', name: 'Ad ID' },
  { id: 'ad_name', name: 'Ad Name' },
  { id: 'date_start', name: 'Date Start' },
  { id: 'date_stop', name: 'Date Stop' },
  { id: 'objective', name: 'Objective' },
  { id: 'impressions', name: 'Impressions' },
  { id: 'clicks', name: 'Clicks' },
  { id: 'call_to_action_clicks', name: 'Call To Action Clicks' },
  { id: 'inline_link_clicks', name: 'Inline Link Clicks' },
  { id: 'cost_per_inline_link_click', name: 'Cost per Inline Link Click' },
  { id: 'cost_per_unique_inline_link_click', name: 'Cost per Unique Inline Link Click' },
  { id: 'ctr', name: 'CTR' },
  { id: 'inline_link_click_ctr', name: 'Inline Link Click CTR' },
  { id: 'unique_clicks', name: 'Unique Clicks' },
  { id: 'unique_ctr', name: 'Unique CTR' },
  { id: 'spend', name: 'Spend' },
  { id: 'frequency', name: 'Frequency' },
  { id: 'reach', name: 'Reach' },
  { id: 'social_reach', name: 'Social Reach' },
  { id: 'relevance_score', name: 'Relevance Score' },
  // Video Engagement
  { id: 'actions', name: '3-Second Video Views' },
  { id: 'video_10_sec_watched_actions', name: '10-Second Video Views' },
  { id: 'cost_per_10_sec_video_view', name: 'Cost per 10-Second Video View' },
  { id: 'video_avg_percent_watched_actions', name: 'Video Percentage Watched' },
  { id: 'video_p25_watched_actions', name: 'Video Watches at 25%' },
  { id: 'video_p50_watched_actions', name: 'Video Watches at 50%' },
  { id: 'video_p75_watched_actions', name: 'Video Watches at 75%' },
  { id: 'video_p95_watched_actions', name: 'Video Watches at 95%' },
  { id: 'video_p100_watched_actions', name: 'Video Watches at 100%' },
];
