export default [
  'age',
  'country',
  'gender',
  'frequency_value',
  'hourly_stats_aggregated_by_advertiser_time_zone',
  'hourly_stats_aggregated_by_audience_time_zone',
  'impression_device',
  'place_page_id',
  'placement',
  'publisher_platform',
  'platform_position',
  'device_platform',
  'product_id',
  'region',
];
